# Generated by Django 2.1.7 on 2020-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created_at',
        ),
    ]
